/**:
  ros__parameters:
    hw_platform: laptop
    use_axis_camera: false
controller:
  ros__parameters:
    base_frame: base_link
    baudrate: 115200
    odom_frame: odom
    publish_tf: true
    read_data:
      list:
      - v_batt
      - motor_status
      motor_status:
        default: 0
        type: int
      v_batt:
        default: 0.0
        type: double
    robot_type: lizard
    serial_port: /dev/ttyACM0
    use_lizard: true
tf_base_link_imu:
  ros__parameters:
    rotation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    translation:
    - 0.0
    - 0.0
    - 0.0
tf_imu_gnss:
  ros__parameters:
    rotation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    translation:
    - 0.0
    - 0.0
    - 0.0
tf_imu_vsm:
  ros__parameters:
    rotation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    translation:
    - 0.0
    - 0.0
    - 0.0
ublox_gps_node:
  ros__parameters:
    baudrate: 460800
    device: /dev/ttyACM1
    dgnss_mode: 3
    frame_id: gps
    gnss:
      beidou: true
      galileo: true
      glonass: true
      gps: true
    inf:
      all: true
    meas: 5
    publish:
      all: true
      nav:
        pvt: true
        sat: true
    uart1:
      baudrate: 460800
web_ui:
  ros__parameters:
    host: 0.0.0.0
    port: 8080
