ublox_gps_node:
  ros__parameters:
    # 1. STOP THE TUG-OF-WAR
    config_on_startup: false  
    load:
      set_all: false
      initialize: false

    # 2. LOCK THE PIPE
    baudrate: 460800
    uart1:
      baudrate: 460800

    # 3. SILENCE THE NOISE
    publish:
      inf:
        all: false
      nav:
        pvt: true
